import React, { useState, useMemo } from 'react';
import {
  Tag,
  Search,
  Plus,
  Edit2,
  Trash2,
  Hash,
  BookOpen,
  Filter,
  CheckCircle2,
  AlertTriangle,
  X,
  ExternalLink,
  Sparkles,
  ArrowUpDown,
  Layers,
  HelpCircle,
} from 'lucide-react';

export interface KeywordItem {
  id: number;
  name: string;
  slug: string;
  usageCount: number;
  createdAt?: string;
}

interface KeywordsManagerProps {
  keywords: KeywordItem[];
  userRole: 'admin' | 'editor' | 'viewer';
  onRefresh: () => Promise<void>;
  onNotify: (message: string) => void;
  onNavigatePublic?: (slug: string) => void;
}

export const KeywordsManager: React.FC<KeywordsManagerProps> = ({
  keywords,
  userRole,
  onRefresh,
  onNotify,
  onNavigatePublic,
}) => {
  // Search & Filter State
  const [searchQuery, setSearchQuery] = useState('');
  const [filterMode, setFilterMode] = useState<'all' | 'used' | 'unused'>('all');
  const [sortBy, setSortBy] = useState<'usage-desc' | 'name-asc' | 'recent'>('usage-desc');

  // Modals
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [editingKeyword, setEditingKeyword] = useState<KeywordItem | null>(null);
  const [deletingKeyword, setDeletingKeyword] = useState<KeywordItem | null>(null);

  // Form State
  const [formName, setFormName] = useState('');
  const [formSlug, setFormSlug] = useState('');
  const [isSlugAutoGenerated, setIsSlugAutoGenerated] = useState(true);
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Quick slug generator
  const slugify = (text: string) =>
    text
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\-]+/g, '-')
      .replace(/(^-|-$)/g, '');

  const handleNameChange = (val: string) => {
    setFormName(val);
    if (isSlugAutoGenerated) {
      setFormSlug(slugify(val));
    }
  };

  const openCreateModal = () => {
    setFormName('');
    setFormSlug('');
    setIsSlugAutoGenerated(true);
    setFormError(null);
    setIsCreateModalOpen(true);
  };

  const openEditModal = (kw: KeywordItem) => {
    setEditingKeyword(kw);
    setFormName(kw.name);
    setFormSlug(kw.slug);
    setIsSlugAutoGenerated(false);
    setFormError(null);
  };

  // Submit Create or Edit
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    const trimmedName = formName.trim();
    if (!trimmedName) {
      setFormError('Please enter a shastric term name.');
      return;
    }

    const trimmedSlug = formSlug.trim() || slugify(trimmedName);
    if (!trimmedSlug) {
      setFormError('Please provide or generate a valid URL slug.');
      return;
    }

    setIsSubmitting(true);
    try {
      if (editingKeyword) {
        // PUT /api/admin/keywords/:id
        const res = await fetch(`/api/admin/keywords/${editingKeyword.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: trimmedName, slug: trimmedSlug }),
        });
        const data = await res.json();
        if (!res.ok) {
          throw new Error(data.error || 'Failed to update keyword.');
        }
        onNotify(`Updated term #${data.keyword.name}`);
        setEditingKeyword(null);
      } else {
        // POST /api/admin/keywords
        const res = await fetch('/api/admin/keywords', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: trimmedName, slug: trimmedSlug }),
        });
        const data = await res.json();
        if (!res.ok) {
          throw new Error(data.error || 'Failed to create keyword.');
        }
        onNotify(`Added shastric term #${data.keyword.name}`);
        setIsCreateModalOpen(false);
      }
      await onRefresh();
    } catch (err: any) {
      setFormError(err.message || 'An error occurred while saving.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Confirm Delete
  const handleConfirmDelete = async () => {
    if (!deletingKeyword) return;
    setIsSubmitting(true);
    try {
      const res = await fetch(`/api/admin/keywords/${deletingKeyword.id}`, {
        method: 'DELETE',
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to delete term.');
      }
      onNotify(`Removed term #${deletingKeyword.name}`);
      setDeletingKeyword(null);
      await onRefresh();
    } catch (err: any) {
      alert(err.message || 'Failed to delete term.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Filter and Sort Keywords
  const filteredKeywords = useMemo(() => {
    let result = [...keywords];

    // Filter mode
    if (filterMode === 'used') {
      result = result.filter((k) => k.usageCount > 0);
    } else if (filterMode === 'unused') {
      result = result.filter((k) => k.usageCount === 0);
    }

    // Search query
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase().trim();
      result = result.filter(
        (k) => k.name.toLowerCase().includes(query) || k.slug.toLowerCase().includes(query)
      );
    }

    // Sorting
    result.sort((a, b) => {
      if (sortBy === 'usage-desc') {
        if (b.usageCount !== a.usageCount) return b.usageCount - a.usageCount;
        return a.name.localeCompare(b.name);
      }
      if (sortBy === 'name-asc') {
        return a.name.localeCompare(b.name);
      }
      if (sortBy === 'recent') {
        return b.id - a.id;
      }
      return 0;
    });

    return result;
  }, [keywords, searchQuery, filterMode, sortBy]);

  // Summary Metrics
  const metrics = useMemo(() => {
    const total = keywords.length;
    const inUse = keywords.filter((k) => k.usageCount > 0).length;
    const unused = total - inUse;
    const totalReferences = keywords.reduce((sum, k) => sum + (k.usageCount || 0), 0);
    return { total, inUse, unused, totalReferences };
  }, [keywords]);

  const canMutate = userRole === 'admin' || userRole === 'editor';
  const canDelete = userRole === 'admin';

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* 1. Page Header & Primary Action */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-amber-900/40">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="p-1.5 rounded-lg bg-amber-500/10 text-amber-400 border border-amber-500/20">
              <Tag className="w-4 h-4" />
            </span>
            <h2 className="font-['Cinzel',serif] text-2xl sm:text-3xl font-bold text-amber-100 tracking-wide">
              Keywords & Shastric Terms
            </h2>
          </div>
          <p className="text-xs sm:text-sm text-stone-400 font-serif max-w-2xl leading-relaxed">
            Standardized Vedic indexing vocabulary connecting articles, spatial entities, orientation canons, and search queries.
          </p>
        </div>

        {canMutate && (
          <button
            onClick={openCreateModal}
            className="inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-amber-600 via-amber-500 to-amber-600 hover:from-amber-500 hover:to-amber-400 text-stone-950 font-serif font-bold text-xs sm:text-sm shadow-lg shadow-amber-950/40 transition-all cursor-pointer shrink-0"
          >
            <Plus className="w-4 h-4 text-stone-950 stroke-[2.5]" />
            <span>Add Shastric Term</span>
          </button>
        )}
      </div>

      {/* 2. Shastric Knowledge Graph Summary KPI Strip */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <div className="p-4 rounded-2xl bg-[#1A0E08] border border-amber-900/40 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[11px] font-serif text-stone-400 uppercase tracking-wider">Total Terms</p>
            <p className="text-xl sm:text-2xl font-bold font-mono text-amber-200 mt-0.5">{metrics.total}</p>
          </div>
          <div className="w-10 h-10 rounded-xl bg-amber-950/60 border border-amber-800/40 flex items-center justify-center text-amber-400">
            <Hash className="w-5 h-5" />
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-[#1A0E08] border border-amber-900/40 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[11px] font-serif text-stone-400 uppercase tracking-wider">In Active Treatises</p>
            <p className="text-xl sm:text-2xl font-bold font-mono text-emerald-400 mt-0.5">{metrics.inUse}</p>
          </div>
          <div className="w-10 h-10 rounded-xl bg-emerald-950/60 border border-emerald-800/40 flex items-center justify-center text-emerald-400">
            <BookOpen className="w-5 h-5" />
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-[#1A0E08] border border-amber-900/40 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[11px] font-serif text-stone-400 uppercase tracking-wider">Unlinked Terms</p>
            <p className="text-xl sm:text-2xl font-bold font-mono text-amber-500/80 mt-0.5">{metrics.unused}</p>
          </div>
          <div className="w-10 h-10 rounded-xl bg-amber-950/40 border border-amber-900/50 flex items-center justify-center text-amber-500/80">
            <Tag className="w-5 h-5" />
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-[#1A0E08] border border-amber-900/40 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[11px] font-serif text-stone-400 uppercase tracking-wider">Article Citations</p>
            <p className="text-xl sm:text-2xl font-bold font-mono text-amber-300 mt-0.5">{metrics.totalReferences}</p>
          </div>
          <div className="w-10 h-10 rounded-xl bg-amber-950/60 border border-amber-800/40 flex items-center justify-center text-amber-300">
            <Layers className="w-5 h-5" />
          </div>
        </div>
      </div>

      {/* 3. Toolbar: Search, Status Filters & Sorting */}
      <div className="p-3.5 sm:p-4 rounded-2xl bg-[#1A0E08] border border-amber-900/50 shadow-md flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
        {/* Search Input */}
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search keywords or slugs (e.g. Brahmasthan, Ishanya)..."
            className="w-full pl-10 pr-9 py-2.5 rounded-xl bg-[#120804] border border-amber-900/70 text-xs sm:text-sm font-serif text-stone-200 placeholder-stone-500 focus:outline-none focus:border-amber-500 transition-colors"
          />
          {searchQuery && (
            <button
              onClick={() => setSearchQuery('')}
              className="absolute right-3 top-1/2 -translate-y-1/2 text-stone-400 hover:text-stone-200 p-0.5"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          )}
        </div>

        {/* Filter Pills & Sort Selector */}
        <div className="flex flex-wrap items-center gap-2">
          {/* Status Filter Tabs */}
          <div className="inline-flex rounded-xl bg-[#120804] p-1 border border-amber-900/60 text-xs font-serif">
            <button
              onClick={() => setFilterMode('all')}
              className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                filterMode === 'all'
                  ? 'bg-amber-600 text-stone-950 font-bold shadow-xs'
                  : 'text-stone-400 hover:text-stone-200'
              }`}
            >
              All ({keywords.length})
            </button>
            <button
              onClick={() => setFilterMode('used')}
              className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                filterMode === 'used'
                  ? 'bg-amber-600 text-stone-950 font-bold shadow-xs'
                  : 'text-stone-400 hover:text-stone-200'
              }`}
            >
              In Treatises ({metrics.inUse})
            </button>
            <button
              onClick={() => setFilterMode('unused')}
              className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                filterMode === 'unused'
                  ? 'bg-amber-600 text-stone-950 font-bold shadow-xs'
                  : 'text-stone-400 hover:text-stone-200'
              }`}
            >
              Unlinked ({metrics.unused})
            </button>
          </div>

          {/* Sort Selector */}
          <div className="flex items-center gap-1.5 rounded-xl bg-[#120804] px-3 py-1.5 border border-amber-900/60 text-xs font-serif text-stone-300">
            <ArrowUpDown className="w-3.5 h-3.5 text-amber-400 shrink-0" />
            <select
              value={sortBy}
              onChange={(e) => setSortBy(e.target.value as any)}
              className="bg-transparent text-xs text-amber-200 font-serif focus:outline-none cursor-pointer"
            >
              <option value="usage-desc" className="bg-[#1C0F08]">Most Cited First</option>
              <option value="name-asc" className="bg-[#1C0F08]">Alphabetical (A - Z)</option>
              <option value="recent" className="bg-[#1C0F08]">Recently Added</option>
            </select>
          </div>
        </div>
      </div>

      {/* 4. Terms Grid Container */}
      <div className="rounded-2xl bg-[#180C07] border border-amber-900/50 p-4 sm:p-6 shadow-inner">
        {filteredKeywords.length === 0 ? (
          /* Empty State */
          <div className="text-center py-12 px-4 max-w-md mx-auto space-y-3">
            <div className="w-14 h-14 rounded-2xl bg-amber-950/50 border border-amber-800/40 mx-auto flex items-center justify-center text-amber-400">
              <Tag className="w-7 h-7" />
            </div>
            <h3 className="font-['Cinzel',serif] text-lg font-bold text-amber-200">
              {searchQuery ? 'No matching shastric terms' : 'No shastric terms found'}
            </h3>
            <p className="text-xs text-stone-400 font-serif leading-relaxed">
              {searchQuery
                ? `No keywords match "${searchQuery}". Clear your search or create a new shastric term.`
                : 'Get started by creating your canonical indexing vocabulary for Vastu Ritam articles.'}
            </p>
            {canMutate && (
              <button
                onClick={openCreateModal}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-amber-600 hover:bg-amber-500 text-stone-950 text-xs font-serif font-bold shadow-md cursor-pointer transition-all"
              >
                <Plus className="w-4 h-4" />
                <span>Create Term #{searchQuery ? searchQuery : ''}</span>
              </button>
            )}
          </div>
        ) : (
          /* Structured Grid of Shastric Term Cards */
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3.5">
            {filteredKeywords.map((kw) => (
              <div
                key={kw.id}
                className="group relative p-3.5 rounded-xl bg-[#1F100A] hover:bg-[#25140D] border border-amber-900/60 hover:border-amber-700/80 transition-all flex flex-col justify-between shadow-xs hover:shadow-md"
              >
                {/* Top: Name & Usage Badge */}
                <div>
                  <div className="flex items-start justify-between gap-2 mb-1.5">
                    <div className="flex items-center gap-1.5 min-w-0">
                      <span className="text-amber-500/80 font-mono text-xs font-bold">#</span>
                      <h4 className="font-['Marcellus',serif] text-sm font-bold text-amber-100 group-hover:text-amber-300 transition-colors truncate">
                        {kw.name}
                      </h4>
                    </div>

                    {/* Usage count pill */}
                    <span
                      title={`${kw.usageCount} articles link to this shastric term`}
                      className={`shrink-0 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-mono font-medium border ${
                        kw.usageCount > 0
                          ? 'bg-emerald-950/80 text-emerald-300 border-emerald-800/60'
                          : 'bg-stone-900/80 text-stone-500 border-stone-800'
                      }`}
                    >
                      <BookOpen className="w-2.5 h-2.5" />
                      <span>{kw.usageCount}</span>
                    </span>
                  </div>

                  {/* Slug preview */}
                  <p className="font-mono text-[10px] text-stone-500 truncate" title={`/keyword/${kw.slug}`}>
                    /{kw.slug}
                  </p>
                </div>

                {/* Bottom Action Footer */}
                <div className="pt-2.5 mt-2.5 border-t border-amber-950/80 flex items-center justify-between text-xs">
                  <span className="text-[10px] font-mono text-stone-500">ID #{kw.id}</span>

                  <div className="flex items-center gap-1">
                    {onNavigatePublic && (
                      <button
                        onClick={() => onNavigatePublic(kw.slug)}
                        className="p-1 rounded-lg hover:bg-stone-800 text-stone-400 hover:text-amber-300 transition-colors cursor-pointer"
                        title="View filtered articles"
                      >
                        <ExternalLink className="w-3 h-3" />
                      </button>
                    )}

                    {canMutate && (
                      <button
                        onClick={() => openEditModal(kw)}
                        className="p-1 rounded-lg hover:bg-amber-950 text-stone-400 hover:text-amber-300 transition-colors cursor-pointer"
                        title="Edit Term & Slug"
                      >
                        <Edit2 className="w-3 h-3" />
                      </button>
                    )}

                    {canDelete && (
                      <button
                        onClick={() => setDeletingKeyword(kw)}
                        className="p-1 rounded-lg hover:bg-red-950 text-stone-400 hover:text-red-400 transition-colors cursor-pointer"
                        title="Delete Term"
                      >
                        <Trash2 className="w-3 h-3" />
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* 5. Create / Edit Keyword Modal */}
      {(isCreateModalOpen || editingKeyword) && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-[#1C0F08] border-2 border-amber-600/80 rounded-3xl p-6 sm:p-7 shadow-2xl space-y-5 animate-in fade-in zoom-in-95 duration-150">
            {/* Modal Header */}
            <div className="flex items-center justify-between pb-3 border-b border-amber-900/60">
              <div className="flex items-center gap-2">
                <span className="p-1 rounded-lg bg-amber-500/20 text-amber-300">
                  <Tag className="w-4 h-4" />
                </span>
                <h3 className="font-['Cinzel',serif] text-lg font-bold text-amber-200">
                  {editingKeyword ? 'Edit Shastric Term' : 'Add New Shastric Term'}
                </h3>
              </div>
              <button
                onClick={() => {
                  setIsCreateModalOpen(false);
                  setEditingKeyword(null);
                }}
                className="p-1.5 rounded-lg text-stone-400 hover:text-stone-200 hover:bg-stone-800 transition-colors cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Error Banner */}
            {formError && (
              <div className="p-3 rounded-xl bg-red-950/70 border border-red-800/80 text-red-200 text-xs font-serif flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
                <span>{formError}</span>
              </div>
            )}

            {/* Form */}
            <form onSubmit={handleSubmit} className="space-y-4 text-xs font-serif">
              {/* Term Name */}
              <div>
                <label className="block text-stone-300 font-bold uppercase tracking-wider mb-1.5">
                  Term Name <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  required
                  autoFocus
                  value={formName}
                  onChange={(e) => handleNameChange(e.target.value)}
                  placeholder="e.g. Brahmasthan, Prana Vayu, Ishanya"
                  className="w-full px-3.5 py-2.5 rounded-xl bg-[#120804] border border-amber-900/80 text-amber-100 font-serif text-sm placeholder-stone-600 focus:outline-none focus:border-amber-500 transition-colors"
                />
                <p className="text-[11px] text-stone-500 mt-1">
                  Classical Sanskrit or architectural concept as referenced in manuscripts.
                </p>
              </div>

              {/* URL Slug */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-stone-300 font-bold uppercase tracking-wider">
                    URL Slug <span className="text-red-400">*</span>
                  </label>
                  <label className="text-[11px] text-amber-400/80 flex items-center gap-1 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={isSlugAutoGenerated}
                      onChange={(e) => setIsSlugAutoGenerated(e.target.checked)}
                      className="rounded accent-amber-500"
                    />
                    <span>Auto-sync with name</span>
                  </label>
                </div>
                <input
                  type="text"
                  required
                  value={formSlug}
                  onChange={(e) => {
                    setFormSlug(e.target.value);
                    setIsSlugAutoGenerated(false);
                  }}
                  placeholder="e.g. brahmasthan"
                  className="w-full px-3.5 py-2.5 rounded-xl bg-[#120804] border border-amber-900/80 font-mono text-xs text-amber-200 placeholder-stone-600 focus:outline-none focus:border-amber-500 transition-colors"
                />
                <p className="text-[11px] text-stone-500 font-mono mt-1">
                  Canonical URL: <span className="text-amber-400/90">/article?keyword={formSlug || '...'}</span>
                </p>
              </div>

              {/* Buttons */}
              <div className="pt-3 flex items-center justify-end gap-3 border-t border-amber-950">
                <button
                  type="button"
                  onClick={() => {
                    setIsCreateModalOpen(false);
                    setEditingKeyword(null);
                  }}
                  className="px-4 py-2 rounded-xl bg-stone-800 hover:bg-stone-700 text-stone-300 font-bold text-xs cursor-pointer transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="px-5 py-2 rounded-xl bg-amber-600 hover:bg-amber-500 disabled:opacity-50 text-stone-950 font-bold text-xs shadow-md cursor-pointer transition-all flex items-center gap-1.5"
                >
                  {isSubmitting && <span className="w-3 h-3 border-2 border-stone-950 border-t-transparent rounded-full animate-spin" />}
                  <span>{editingKeyword ? 'Save Changes' : 'Create Term'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* 6. Confirm Delete Modal */}
      {deletingKeyword && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="w-full max-w-sm bg-[#1C0F08] border-2 border-red-700/80 rounded-3xl p-6 shadow-2xl space-y-4 animate-in fade-in zoom-in-95 duration-150">
            <div className="w-12 h-12 rounded-2xl bg-red-950/60 border border-red-700/60 mx-auto flex items-center justify-center text-red-400">
              <AlertTriangle className="w-6 h-6" />
            </div>

            <div className="text-center space-y-1.5">
              <h3 className="font-['Cinzel',serif] text-base font-bold text-amber-100">
                Delete Shastric Term #{deletingKeyword.name}?
              </h3>
              <p className="text-xs text-stone-400 font-serif leading-relaxed">
                {deletingKeyword.usageCount > 0 ? (
                  <span className="text-red-300">
                    Warning: This term is actively cited in <strong>{deletingKeyword.usageCount}</strong> article(s). Deleting it will detach it from those treatises in PostgreSQL.
                  </span>
                ) : (
                  'This term is not currently linked to any articles and can be safely removed.'
                )}
              </p>
            </div>

            <div className="pt-2 flex items-center justify-center gap-3">
              <button
                type="button"
                onClick={() => setDeletingKeyword(null)}
                disabled={isSubmitting}
                className="px-4 py-2 rounded-xl bg-stone-800 hover:bg-stone-700 text-stone-300 font-serif font-bold text-xs cursor-pointer transition-colors"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleConfirmDelete}
                disabled={isSubmitting}
                className="px-4 py-2 rounded-xl bg-red-600 hover:bg-red-500 text-white font-serif font-bold text-xs shadow-md cursor-pointer transition-all flex items-center gap-1.5"
              >
                {isSubmitting && <span className="w-3 h-3 border-2 border-white border-t-transparent rounded-full animate-spin" />}
                <span>Confirm Delete</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
